POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "email": "correo@example.com",
    "password": "12345678"
}

###
put http://localhost:3000/api/user/validation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y2MzY2M2MwMTYxZjYzMzBhNDNhOGEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDE4OTAyNywiZXhwIjoxNzQ0Mjc1NDI3fQ.pK9wFSEpmmwTjE4mo2C9LcuoQlnMuLKYFNYdPLHTxmo
Content-Type: application/json

{
    "code": "707151"
}

###
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "correo@example.com",
    "password": "12345678"
}

###
put http://localhost:3000/api/user/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y2MjA5ZTg4MjU4MDA0NjQ3YTVmNzgiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDE4Njc4MCwiZXhwIjoxNzQ0MjczMTgwfQ.R9koSsJws10shetxHIkG8YGB6WCr-lppKwYgi-e8q1Y
Content-Type: application/json

{
    "email": "correo1@example.com",
    "name": "qunjieye",
    "nif": "40000000Q"
}

###
patch http://localhost:3000/api/user/company
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y2MjA5ZTg4MjU4MDA0NjQ3YTVmNzgiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDE4Njc4MCwiZXhwIjoxNzQ0MjczMTgwfQ.R9koSsJws10shetxHIkG8YGB6WCr-lppKwYgi-e8q1Y
Content-Type: application/json

{
  "company": {
    "street": "Carlos s67",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid",
    "name": "qunjieyse",
    "cif": "40000000Q"
  }
}



###
PATCH  http://localhost:3000/api/user/logo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y2MjA5ZTg4MjU4MDA0NjQ3YTVmNzgiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDE4Njc4MCwiZXhwIjoxNzQ0MjczMTgwfQ.R9koSsJws10shetxHIkG8YGB6WCr-lppKwYgi-e8q1Y
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="image"; filename="login.jpg"
Content-Type: image/jpeg

< ./login.jpg
--boundary123--

###
get http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y2MzY2M2MwMTYxZjYzMzBhNDNhOGEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDE4OTAyNywiZXhwIjoxNzQ0Mjc1NDI3fQ.pK9wFSEpmmwTjE4mo2C9LcuoQlnMuLKYFNYdPLHTxmo
Content-Type: application/json


###
delete http://localhost:3000/api/user?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y2MzY2M2MwMTYxZjYzMzBhNDNhOGEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDE4OTAyNywiZXhwIjoxNzQ0Mjc1NDI3fQ.pK9wFSEpmmwTjE4mo2C9LcuoQlnMuLKYFNYdPLHTxmo
Content-Type: application/json


###
get http://localhost:3000/api/user/codePassword
Content-Type: application/json

{
    "email": "qunjieye@example.com"
}

###
patch http://localhost:3000/api/user/password
Content-Type: application/json

{
    "email": "qunjieye@example.com",
    "code": 632982,
    "password" : "12345678"
}

###
post http://localhost:3000/api/user/invite
Content-Type: application/json

{
    "email": "invitado@example.com",
    "password": "12345678",
    "company": {
      "name":"qunjieye"
    }
}

###
get http://localhost:3000/api/user/users
Content-Type: application/json
